# Generated by Django 4.2 on 2023-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaHoaDon', max_length=10)),
                ('manhacungcap', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaNhaCungCap', max_length=10, null=True)),
                ('ngaynhap', models.DateField(blank=True, db_column='NgayNhap', null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('datra', models.IntegerField(blank=True, db_column='DaTra', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madonhang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaDonHang', max_length=10)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('matrahang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaTraHang', max_length=10, null=True)),
                ('loaikhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LoaiKhachHang', max_length=50, null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('giamgia', models.IntegerField(blank=True, db_column='GiamGia', null=True)),
                ('khachhangtra', models.IntegerField(blank=True, db_column='KhachHangTra', null=True)),
            ],
            options={
                'db_table': 'Bill_of_Sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtCllectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhachhang', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenKhachHang', null=True)),
                ('congnodauky', models.IntegerField(blank=True, db_column='CongNoDauKy', null=True)),
                ('congnocuoiky', models.IntegerField(blank=True, db_column='CongNoCuoiky', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=10, null=True)),
                ('tungay', models.DateField(db_column='TuNgay')),
                ('denngay', models.DateField(db_column='DenNgay')),
            ],
            options={
                'db_table': 'Debt_Cllection_Report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtPaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhacungcap', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenNhaCungCap', null=True)),
                ('congnodauky', models.IntegerField(blank=True, db_column='CongNoDauKy', null=True)),
                ('congnocuoiky', models.IntegerField(blank=True, db_column='CongNoCuoiKy', null=True)),
                ('trangthai', models.IntegerField(blank=True, db_column='TrangThai', null=True)),
                ('tungay', models.DateField(db_column='TuNgay')),
                ('denngay', models.DateField(db_column='DenNgay')),
            ],
            options={
                'db_table': 'Debt_Payment_Report',
                'managed': False,
            },
        ),
    ]
