# Generated by Django 4.2 on 2023-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maphieuchuyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaPhieuChuyen', max_length=10)),
                ('tudiadiem', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TuDiaDiem', null=True)),
                ('dendiadiem', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DenDiaDiem', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaHoaDon', max_length=10)),
                ('manhacungcap', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaNhaCungCap', max_length=10, null=True)),
                ('ngaynhap', models.DateField(blank=True, db_column='NgayNhap', null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('datra', models.IntegerField(blank=True, db_column='DaTra', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfReturnGoodsBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytra', models.DateField(blank=True, db_column='NgayTra', null=True)),
                ('tenncc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenNCC', null=True)),
                ('tongtienhangtra', models.IntegerField(blank=True, db_column='TongTienHangTra', null=True)),
                ('tongtienncccantra', models.IntegerField(blank=True, db_column='TongTienNCCCanTra', null=True)),
                ('nccdatra', models.IntegerField(blank=True, db_column='NCCDaTra', null=True)),
                ('trangthai', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', null=True)),
            ],
            options={
                'db_table': 'Bill_of_Return_Goods_Back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfReturnTheGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrahang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaTraHang', max_length=10)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('makhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaKhachHang', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Return_the_Goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madonhang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaDonHang', max_length=10)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('matrahang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaTraHang', max_length=10, null=True)),
                ('loaikhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LoaiKhachHang', max_length=50, null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('giamgia', models.IntegerField(blank=True, db_column='GiamGia', null=True)),
                ('khachhangtra', models.IntegerField(blank=True, db_column='KhachHangTra', null=True)),
            ],
            options={
                'db_table': 'Bill_of_Sale',
                'managed': False,
            },
        ),
    ]
