# Generated by Django 4.2 on 2023-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaHoaDon', max_length=10)),
                ('manhacungcap', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaNhaCungCap', max_length=10, null=True)),
                ('ngaynhap', models.DateField(blank=True, db_column='NgayNhap', null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('datra', models.IntegerField(blank=True, db_column='DaTra', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Import',
                'managed': False,
            },
        ),
    ]
