# Generated by Django 4.2 on 2023-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maphieuchuyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaPhieuChuyen', max_length=10)),
                ('tudiadiem', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TuDiaDiem', null=True)),
                ('dendiadiem', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DenDiaDiem', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaHoaDon', max_length=10)),
                ('manhacungcap', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaNhaCungCap', max_length=10, null=True)),
                ('ngaynhap', models.DateField(blank=True, db_column='NgayNhap', null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('datra', models.IntegerField(blank=True, db_column='DaTra', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfReturnGoodsBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytra', models.DateField(blank=True, db_column='NgayTra', null=True)),
                ('tenncc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenNCC', null=True)),
                ('tongtienhangtra', models.IntegerField(blank=True, db_column='TongTienHangTra', null=True)),
                ('tongtienncccantra', models.IntegerField(blank=True, db_column='TongTienNCCCanTra', null=True)),
                ('nccdatra', models.IntegerField(blank=True, db_column='NCCDaTra', null=True)),
                ('trangthai', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', null=True)),
            ],
            options={
                'db_table': 'Bill_of_Return_Goods_Back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfReturnTheGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrahang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaTraHang', max_length=10)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('makhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaKhachHang', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Bill_of_Return_the_Goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madonhang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaDonHang', max_length=10)),
                ('thoigian', models.DateField(blank=True, db_column='ThoiGian', null=True)),
                ('matrahang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaTraHang', max_length=10, null=True)),
                ('loaikhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LoaiKhachHang', max_length=50, null=True)),
                ('tongtien', models.IntegerField(blank=True, db_column='TongTien', null=True)),
                ('giamgia', models.IntegerField(blank=True, db_column='GiamGia', null=True)),
                ('khachhangtra', models.IntegerField(blank=True, db_column='KhachHangTra', null=True)),
            ],
            options={
                'db_table': 'Bill_of_Sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makhachhang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaKhachHang', max_length=10)),
                ('tenkhachhang', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenKhachHang', null=True)),
                ('masothue', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaSoThue', max_length=10, null=True)),
                ('dienthoai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DienThoai', max_length=12, null=True)),
                ('gioitinh', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GioiTinh', max_length=50, null=True)),
                ('ngaysinh', models.DateField(blank=True, db_column='NgaySinh', null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=255, null=True)),
                ('congty', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CongTy', null=True)),
                ('diachi', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DiaChi', null=True)),
                ('loaikhachhang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LoaiKhachHang', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtCllectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhachhang', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenKhachHang', null=True)),
                ('congnodauky', models.IntegerField(blank=True, db_column='CongNoDauKy', null=True)),
                ('congnocuoiky', models.IntegerField(blank=True, db_column='CongNoCuoiky', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TrangThai', max_length=10, null=True)),
                ('tungay', models.DateField(db_column='TuNgay')),
                ('denngay', models.DateField(db_column='DenNgay')),
            ],
            options={
                'db_table': 'Debt_Cllection_Report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebtPaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhacungcap', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenNhaCungCap', null=True)),
                ('congnodauky', models.IntegerField(blank=True, db_column='CongNoDauKy', null=True)),
                ('congnocuoiky', models.IntegerField(blank=True, db_column='CongNoCuoiKy', null=True)),
                ('trangthai', models.IntegerField(blank=True, db_column='TrangThai', null=True)),
                ('tungay', models.DateField(db_column='TuNgay')),
                ('denngay', models.DateField(db_column='DenNgay')),
            ],
            options={
                'db_table': 'Debt_Payment_Report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makiemkho', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaKiemKho', max_length=10)),
                ('thoigiankiemkho', models.DateField(blank=True, db_column='ThoiGianKiemKho', null=True)),
                ('mahang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaHang', max_length=10, null=True)),
                ('so_luong_ton_kho', models.IntegerField(blank=True, db_column='So_Luong_Ton_Kho', null=True)),
                ('danh_gia_thuoc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Danh_Gia_Thuoc', null=True)),
            ],
            options={
                'db_table': 'Drug_Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresicriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateField(blank=True, db_column='Ngay_Nhap', null=True)),
                ('ma_thuoc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ma_Thuoc', max_length=10)),
                ('ten_thuoc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ten_Thuoc', null=True)),
                ('don_vi', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Don_Vi', null=True)),
                ('so_luong_dung', models.IntegerField(blank=True, db_column='So_Luong_Dung', null=True)),
                ('lieu_dung', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lieu_Dung', null=True)),
                ('trang_thai_thuoc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Trang_Thai_Thuoc', null=True)),
                ('ghi_chu', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ghi_Chu', null=True)),
            ],
            options={
                'db_table': 'Presicription_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ma_Hang', max_length=10)),
                ('ten_hang', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ten_Hang', null=True)),
                ('don_vi', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Don_Vi', max_length=50, null=True)),
                ('gia_goc', models.IntegerField(blank=True, db_column='Gia_Goc', null=True)),
                ('gia_ban', models.IntegerField(blank=True, db_column='Gia_Ban', null=True)),
                ('so_luong_ton_kho', models.IntegerField(blank=True, db_column='So_Luong_Ton_Kho', null=True)),
                ('trang_thai', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Trang_Thai', null=True)),
            ],
            options={
                'db_table': 'Product_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('manhacungcap', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaNhaCungCap', max_length=10)),
                ('tenncc', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TenNCC', null=True)),
                ('email', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', null=True)),
                ('dienthoai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DienThoai', max_length=12, null=True)),
                ('congty', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CongTy', null=True)),
                ('diachi', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DiaChi', null=True)),
                ('masothue', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaSoThue', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
    ]
